### ISSUE TITLE
ImportError: cannot import name emails

### ISSUE THREAD

**Issue by KDPryor** [woj-ciech/Danger-zone#1]
Hello,
Tried running the code and got the error noted in the subject line. Here's the full output:

`Traceback (most recent call last):
  File "./danger-zone.py", line 5, in <module>
    import utils
  File "/mnt/c/Users/Ken/Documents/GitHub/Danger-zone/utils.py", line 2, in <module>
    import emails
  File "/mnt/c/Users/Ken/Documents/GitHub/Danger-zone/emails.py", line 5, in <module>
    from google import google
ImportError: cannot import name google`

Changing "import emails" to "import email" in utils.py stops this error but then new errors come up later in the process. My Python skills aren't good enough to figure it out from there.

**Comment by woj-ciech** [comment]
Same as https://github.com/woj-ciech/Danger-zone/issues/2
