### ISSUE TITLE
NameError: global name 'google' is not defined

### ISSUE THREAD

**Issue by data-source** [woj-ciech/Danger-zone#2]
input as follows: 
`python danger-zone.py --email user@domain.com`

Error: 
`Traceback (most recent call last):
  File "danger-zone.py", line 41, in <module>
    domains_from_email = util.get_domain_from_email(email, elastic_output)
  File "/Danger-zone-master/utils.py", line 46, in get_domain_from_email
    email1.google()
  File "/Danger-zone-master/emails.py", line 146, in google
    search_results = google.search("\"" + self.email_address + "\"", 1)
NameError: global name 'google' is not defined` 

Had earlier error 
`ImportError: cannot import name google` 
so changed import in emails.py to:  
`from google import *`

**Comment by woj-ciech** [comment]
Wrong module, should be Google-search-api. Updated Readme.md https://github.com/woj-ciech/Danger-zone/commit/a4e4937c2de8dca13f3ac21ede510acde433e948
