### ISSUE TITLE
Installed on mac, shows only the info, no requests.

### ISSUE THREAD

**Issue by TigeKala** [woj-ciech/Danger-zone#8]
Do i have to make open port to firewall or what?

**Comment by woj-ciech** [comment]
Hey, can you elaborate? I don't know what you mean by that. 
Can you upload some screens/input value/outputs? Which ports you are talking about?

**Comment by TigeKala** [comment]
Hi, it was my own stupidity, sorry forgot to close - had to make danger-zone.py executable :)

**Comment by woj-ciech** [comment]
Sure, I'm happy it works :)
