### ISSUE TITLE
HTTP calls to several apis that have TLS

### ISSUE THREAD

**Issue by catten** [woj-ciech/Danger-zone#9]
I would prefer TLS when available

**Comment by woj-ciech** [comment]
Hey,
Updated, please find https://github.com/woj-ciech/Danger-zone/commit/80da9ddf48662391483ece8a07afc13e77542eb2 and https://github.com/woj-ciech/Danger-zone/commit/45dd8918d71c88e3306babbeaf8110e6cfa147e7
Thanks for heads-up!
